version: '3'
services:


##########
  motioneye:
      container_name: motioneye
      image: ccrisan/motioneye:master-amd64
      restart: always
      environment:
        - TZ=Pacific/Auckland
      volumes:
        - /etc/localtime:/etc/localtime
        - /etc/motioneye:/etc/motioneye
        - /var/lib/motioneye:/var/lib/motioneye
      ports:
        - 8765:8765
        - 18081:8081
        - 18082:8082
        - 18083:8083

##########


##########
  hass:
      container_name: hass
      image: homeassistant/home-assistant:stable
      restart: always
      environment:
        - TZ=Pacific/Auckland
      volumes:
        - /home/hass/config:/config
#    network_mode: host
      ports:
        - 8123:8123

#########


#########
#smokeping:
#version: "2.1"
#services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
#    #- PUID=1000
#    #- PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/smokeping/config:/config:ro
      - /home/smokeping/data:/data
    ports:
      - 8124:80
    restart: unless-stopped
#########

#########
#Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8125:80
      - 443:443
    environment:
      - TZ=Pacific/Auckland

##########

##########

  netdata:
     container_name: netdata
     image: netdata/netdata
     restart: always
     ports:
       - 19999:19999
     cap_add:
       - SYS_PTRACE
     security_opt:
       - apparmor:unconfined
     volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
     environment:
       - PGID=133

