version: '3'
services:


##########
  motioneye:
      container_name: motioneye
      image: ccrisan/motioneye:master-amd64
      restart: always
      environment:
        - TZ=Pacific/Auckland
      volumes:
        - /etc/localtime:/etc/localtime
        - /etc/motioneye:/etc/motioneye
        - /var/lib/motioneye:/var/lib/motioneye
      ports:
        - 8765:8765
        - 18081:8081
        - 18082:8082
        - 18083:8083

##########


##########
  hass:
      container_name: hass
      image: homeassistant/home-assistant:stable
      restart: always
      environment:
        - TZ=Pacific/Auckland
      volumes:
        - /home/hass/config:/config
#    network_mode: host
      ports:
        - 8123:8123

#########


#########
#smokeping:
#version: "2.1"
#services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
#    #- PUID=1000

